import numpy as np
import random
import string
import vigenere
import substitution
import statistics
import transposition

def generate_data(count):
    data = []
    labels = []

    config = {"vigenere": 0,
              "substitution": 1,
              "transposition": 2

        }

    pt = list('TOSHERLOCKHOLMESSHEISALWAYSTHEWOMANIHAVESELDOMHEARDHIMMENTIONHERUNDERANYOTHERNAMEINHISEYESSHEECLIPSESANDPREDOMINATESTHEWHOLEOFHERSEXITWASNOTTHATHEFELTANYEMOTIONAKINTOLOVEFORIRENEADLERALLEMOTIONSANDTHATONEPARTICULARLYWEREABHORRENTTOHISCOLDPRECISEBUTADMIRABLYBALANCEDMINDHEWASITAKEITTHEMOSTPERFECTREASONINGANDOBSERVINGMACHINETHATTHEWORLDHASSEENBUTASALOVERHEWOULDHAVEPLACEDHIMSELFINAFALSEPOSITIONHENEVERSPOKEOFTHESOFTERPASSIONSSAVEWITHAGIBEANDASNEERTHEYWEREADMIRABLETHINGSFORTHEOBSERVEREXCELLENTFORDRAWINGTHEVEILFROMMENSMOTIVESANDACTIONSBUTFORTHETRAINEDREASONERTOADMITSUCHINTRUSIONSINTOHISOWNDELICATEANDFINELYADJUSTEDTEMPERAMENTWASTOINTRODUCEADISTRACTINGFACTORWHICHMIGHTTHROWADOUBTUPONALLHISMENTALRESULTSGRITINASENSITIVEINSTRUMENTORACRACKINONEOFHISOWNHIGHPOWERLENSESWOULDNOTBEMOREDISTURBINGTHANASTRONGEMOTIONINANATURESUCHASHISANDYETTHEREWASBUTONEWOMANTOHIMANDTHATWOMANWASTHELATEIRENEADLEROFDUBIOUSANDQUESTIONABLEMEMORYIHADSEENLITTLEOFHOLMESLATELYMYMARRIAGEHADDRIFTEDUSAWAYFROMEACHOTHERMYOWNCOMPLETEHAPPINESSANDTHEHOMECENTREDINTERESTSWHICHRISEUPAROUNDTHEMANWHOFIRSTFINDSHIMSELFMASTEROFHISOWNESTABLISHMENTWERESUFFICIENTTOABSORBALLMYATTENTIONWHILEHOLMESWHOLOATHEDEVERYFORMOFSOCIETYWITHHISWHOLEBOHEMIANSOULREMAINEDINOURLODGINGSINBAKERSTREETBURIEDAMONGHISOLDBOOKSANDALTERNATINGFROMWEEKTOWEEKBETWEENCOCAINEANDAMBITIONTHEDROWSINESSOFTHEDRUGANDTHEFIERCEENERGYOFHISOWNKEENNATUREHEWASSTILLASEVERDEEPLYATTRACTEDBYTHESTUDYOFCRIMEANDOCCUPIEDHISIMMENSEFACULTIESANDEXTRAORDINARYPOWERSOFOBSERVATIONINFOLLOWINGOUTTHOSECLUESANDCLEARINGUPTHOSEMYSTERIESWHICHHADBEENABANDONEDASHOPELESSBYTHEOFFICIALPOLICEFROMTIMETOTIMEIHEARDSOMEVAGUEACCOUNTOFHISDOINGSOFHISSUMMONSTOODESSAINTHECASEOFTHETREPOFFMURDEROFHISCLEARINGUPOFTHESINGULARTRAGEDYOFTHEATKINSONBROTHERSATTRINCOMALEEANDFINALLYOFTHEMISSIONWHICHHEHADACCOMPLISHEDSODELICATELYANDSUCCESSFULLYFORTHEREIGNINGFAMILYOFHOLLANDBEYONDTHESESIGNSOFHISACTIVITYHOWEVERWHICHIMERELYSHAREDWITHALLTHEREADERSOFTHEDAILYPRESSIKNEWLITTLEOFMYFORMERFRIENDANDCOMPANIONONENIGHTITWASONTHETWENTIETHOFMARCHIWASRETURNINGFROMAJOURNEYTOAPATIENTFORIHADNOWRETURNEDTOCIVILPRACTICEWHENMYWAYLEDMETHROUGHBAKERSTREETASIPASSEDTHEWELLREMEMBEREDDOORWHICHMUSTALWAYSBEASSOCIATEDINMYMINDWITHMYWOOINGANDWITHTHEDARKINCIDENTSOFTHESTUDYINSCARLETIWASSEIZEDWITHAKEENDESIRETOSEEHOLMESAGAINANDTOKNOWHOWHEWASEMPLOYINGHISEXTRAORDINARYPOWERSHISROOMSWEREBRILLIANTLYLITANDEVENASILOOKEDUPISAWHISTALLSPAREFIGUREPASSTWICEINADARKSILHOUETTEAGAINSTTHEBLINDHEWASPACINGTHEROOMSWIFTLYEAGERLYWITHHISHEADSUNKUPONHISCHESTANDHISHANDSCLASPEDBEHINDHIMTOMEWHOKNEWHISEVERYMOODANDHABITHISATTITUDEANDMANNERTOLDTHEIROWNSTORYHEWASATWORKAGAINHEHADRISENOUTOFHISDRUGCREATEDDREAMSANDWASHOTUPONTHESCENTOFSOMENEWPROBLEMIRANGTHEBELLANDWASSHOWNUPTOTHECHAMBERWHICHHADFORMERLYBEENINPARTMYOWNHISMANNERWASNOTEFFUSIVEITSELDOMWASBUTHEWASGLADITHINKTOSEEMEWITHHARDLYAWORDSPOKENBUTWITHAKINDLYEYEHEWAVEDMETOANARMCHAIRTHREWACROSSHISCASEOFCIGARSANDINDICATEDASPIRITCASEANDAGASOGENEINTHECORNERTHENHESTOODBEFORETHEFIREANDLOOKEDMEOVERINHISSINGULARINTROSPECTIVEFASHION')

    print("Generating vigenere")
    for keyLen in range(2,15):
        key = random.sample(list(string.ascii_uppercase), keyLen)

        for x in range(count):
            random.shuffle(key)
            data.append(vigenere.encrypt_vigenere(pt, key))
            labels.append(config["vigenere"])
    print("Generating substitution")

    key = list(string.ascii_uppercase)
    for x in range(count):
        random.shuffle(key)
        data.append(substitution.encrypt_substitution(pt, key))
        labels.append(config["substitution"])

    print("Generating transposition")
    for keyLen in range(2,15):
        key = list(range(keyLen))
        for x in range(count):
            random.shuffle(key)
            data.append(transposition.encrypt_transposition(pt, key))
            labels.append(config["transposition"])

    print("Generating statistics")
    return np.array(list(map(lambda x: [func(x) for func in statistics.stats_funcs], data))), np.asarray(labels)
        


    
